// server/src/services/seedService.ts
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

export async function seedScenario(db = prisma) {
  console.log('--- Starting TRINETRA Pan-India Comprehensive Scenario Seeding (SIH 26206) ---');

  // Clean dynamic tables in dependency order
  await db.floodBuffer.deleteMany();
  await db.auditLog.deleteMany();
  await db.incidentReport.deleteMany();
  await db.alert.deleteMany();
  await db.riskAssessment.deleteMany();
  await db.safeZone.deleteMany();
  await db.emergencyResource.deleteMany();
  await db.disaster.deleteMany();
  await db.user.deleteMany();

  const salt = await bcrypt.genSalt(10);
  const commonPasswordHash = await bcrypt.hash('Password123!', salt);

  // 1. Seed Core Users
  const authorityUser = await db.user.create({
    data: {
      email: 'authority@trinetra.gov.in',
      passwordHash: commonPasswordHash,
      fullName: 'Director S. K. Sharma',
      phone: '+91 94350 12345',
      role: 'AUTHORITY',
      badgeNumber: 'NDMA-DIR-088',
      department: 'National & State Disaster Management Authorities',
    },
  });

  const citizenUser = await db.user.create({
    data: {
      email: 'citizen@example.com',
      passwordHash: commonPasswordHash,
      fullName: 'Abhinav Verma',
      phone: '+91 98765 43210',
      role: 'CITIZEN',
    },
  });

  const responderUser = await db.user.create({
    data: {
      email: 'responder@ndrf.gov.in',
      passwordHash: commonPasswordHash,
      fullName: 'Inspector R. K. Singh',
      phone: '+91 98111 22334',
      role: 'RESPONDER',
      badgeNumber: 'NDRF-INS-142',
      department: 'National Disaster Response Force (NDRF HQ)',
    },
  });

  const adminUser = await db.user.create({
    data: {
      email: 'admin@trinetra.gov.in',
      passwordHash: commonPasswordHash,
      fullName: 'National Command Administrator',
      phone: '+91 98999 11223',
      role: 'ADMIN',
      badgeNumber: 'NDMA-HQ-001',
      department: 'National Disaster Management Authority (NDMA)',
    },
  });

  console.log('✓ Users created: Admin, Authority, Citizen, Responder');

  // 2. Seed Pan-India Active Disaster Scenarios
  const disastersData = [
    {
      title: 'Brahmaputra River Inundation & Embankment Breach',
      type: 'FLOOD',
      severity: 'CRITICAL',
      status: 'ACTIVE',
      locationName: 'Guwahati, Kamrup Metropolitan, Assam',
      latitude: 26.1445,
      longitude: 91.7362,
      radiusKm: 25.0,
      description:
        'Water level in River Brahmaputra crossed danger level (51.5m). Severe inundation reported across low-lying wards with partial embankment failure near Pandu Ghat.',
      affectedPopulationEst: 140000,
      source: 'Central Water Commission (CWC) & ASDMA Operations Center',
      declaredAt: new Date(Date.now() - 6 * 3600 * 1000),
    },
    {
      title: 'Yamuna River Surge & Low-Lying Inundation',
      type: 'FLOOD',
      severity: 'HIGH',
      status: 'ACTIVE',
      locationName: 'Kashmere Gate & Yamuna Floodplain, New Delhi',
      latitude: 28.6692,
      longitude: 77.2315,
      radiusKm: 18.0,
      description:
        'Yamuna river level breached evacuation threshold of 206.5m following 3.2 lakh cusecs discharge from Hathnikund Barrage. Flood water inundating low-lying ghats and ring road sectors.',
      affectedPopulationEst: 85000,
      source: 'Delhi Disaster Management Authority (DDMA)',
      declaredAt: new Date(Date.now() - 10 * 3600 * 1000),
    },
    {
      title: 'Alaknanda Basin Flash Flood & Chamoli Landslide Hazard',
      type: 'LANDSLIDE',
      severity: 'CRITICAL',
      status: 'ACTIVE',
      locationName: 'Chamoli / Joshimath Valley, Uttarakhand',
      latitude: 30.5562,
      longitude: 79.5670,
      radiusKm: 22.0,
      description:
        'Torrential cloudburst in upper catchment triggered debris avalanche and massive rockfall near Helang-Joshimath sector. Rishikesh-Badrinath highway blocked; slope sensors indicate active displacement.',
      affectedPopulationEst: 35000,
      source: 'Uttarakhand State Disaster Management Authority (USDMA)',
      declaredAt: new Date(Date.now() - 14 * 3600 * 1000),
    },
    {
      title: 'Beas River Surge & Cloudburst Advisory',
      type: 'FLOOD',
      severity: 'HIGH',
      status: 'ACTIVE',
      locationName: 'Kullu & Manali Riverfront, Himachal Pradesh',
      latitude: 31.9579,
      longitude: 77.1095,
      radiusKm: 20.0,
      description:
        'Sudden cloudburst in Solang valley triggered sharp water surge in River Beas. Riverside campings and market structures inundated. Evacuation underway towards high-ground shelters.',
      affectedPopulationEst: 45000,
      source: 'Himachal Pradesh SDMA & IMD Shimla',
      declaredAt: new Date(Date.now() - 8 * 3600 * 1000),
    },
    {
      title: 'Severe Cyclonic Storm "Sagar" Coastal Buffer',
      type: 'CYCLONE',
      severity: 'CRITICAL',
      status: 'ACTIVE',
      locationName: 'Puri & Paradip Coastal Corridor, Odisha',
      latitude: 19.8135,
      longitude: 85.8312,
      radiusKm: 35.0,
      description:
        'Deep depression over Bay of Bengal intensified into Severe Cyclonic Storm with sustained winds of 115-125 km/h. High tidal surges of 2.5m predicted along Puri and Jagatsinghpur coastline.',
      affectedPopulationEst: 220000,
      source: 'India Meteorological Department (IMD) & OSDMA',
      declaredAt: new Date(Date.now() - 12 * 3600 * 1000),
    },
    {
      title: 'Mithi River Urban Deluge & Coastal High Tide Alert',
      type: 'URBAN_EMERGENCY',
      severity: 'HIGH',
      status: 'ACTIVE',
      locationName: 'Kurla, BKC & Sion Basin, Mumbai, Maharashtra',
      latitude: 19.0760,
      longitude: 72.8777,
      radiusKm: 15.0,
      description:
        'Over 210mm rainfall recorded in 12 hours coinciding with 4.87m astronomical high tide. Kurla, Sion, and Hindmata under severe urban waterlogging with localized power shutoffs.',
      affectedPopulationEst: 310000,
      source: 'BMC Disaster Control Room & IMD Mumbai',
      declaredAt: new Date(Date.now() - 5 * 3600 * 1000),
    },
    {
      title: 'Western Ghats Debris Flow & Landslide Emergency',
      type: 'LANDSLIDE',
      severity: 'CRITICAL',
      status: 'ACTIVE',
      locationName: 'Chooralmala & Meppadi, Wayanad, Kerala',
      latitude: 11.5534,
      longitude: 76.1320,
      radiusKm: 16.0,
      description:
        'Extremely heavy rainfall (320mm in 24 hours) triggered severe hill slope collapse and mudslides in Chooralmala and Meppadi valleys. Multiple local roads and bridge culverts washed away.',
      affectedPopulationEst: 28000,
      source: 'Kerala State Disaster Management Authority (KSDMA)',
      declaredAt: new Date(Date.now() - 18 * 3600 * 1000),
    },
    {
      title: 'Northeast Monsoon Depression & Urban Inundation',
      type: 'FLOOD',
      severity: 'HIGH',
      status: 'ACTIVE',
      locationName: 'Velachery & Adyar Basin, Chennai, Tamil Nadu',
      latitude: 13.0827,
      longitude: 80.2707,
      radiusKm: 20.0,
      description:
        'Intense coastal convective storm bands dumped 185mm rain. Adyar and Cooum river basins flowing near capacity; inundation in Velachery, Mudichur, and Madipakkam.',
      affectedPopulationEst: 175000,
      source: 'Greater Chennai Corporation & TNSDMA',
      declaredAt: new Date(Date.now() - 7 * 3600 * 1000),
    },
    {
      title: 'Sundarbans Tidal Inundation & Embankment Vulnerability',
      type: 'CYCLONE',
      severity: 'HIGH',
      status: 'ACTIVE',
      locationName: 'Gosaba & South 24 Parganas, West Bengal',
      latitude: 22.1890,
      longitude: 88.8003,
      radiusKm: 30.0,
      description:
        'Full moon spring tide combined with Bay of Bengal squally weather breached earthen river embankments in Gosaba and Kakdwip, flooding agricultural lands and fishing settlements.',
      affectedPopulationEst: 95000,
      source: 'West Bengal Disaster Management & Civil Defence',
      declaredAt: new Date(Date.now() - 16 * 3600 * 1000),
    },
    {
      title: 'Kosi & Ganga River Confluence Flood Spate',
      type: 'FLOOD',
      severity: 'CRITICAL',
      status: 'ACTIVE',
      locationName: 'Supaul, Saharsa & Patna Diara, Bihar',
      latitude: 25.5941,
      longitude: 85.1376,
      radiusKm: 28.0,
      description:
        'Massive water discharge (3.7 lakh cusecs) released from Birpur Barrage. Widespread flood inundation in Supaul, Saharsa, and river diara islands along Patna district.',
      affectedPopulationEst: 190000,
      source: 'Bihar State Disaster Management Authority (BSDMA)',
      declaredAt: new Date(Date.now() - 11 * 3600 * 1000),
    },
    {
      title: 'Arabian Sea Coastal Gale & Wave Surge Warning',
      type: 'CYCLONE',
      severity: 'MEDIUM',
      status: 'ACTIVE',
      locationName: 'Dwarka & Jamnagar Coastline, Gujarat',
      latitude: 22.2442,
      longitude: 68.9685,
      radiusKm: 25.0,
      description:
        'Cyclonic circulation over Northeast Arabian Sea causing rough sea conditions with waves reaching 3.8m. Deep-sea fishing strictly suspended and coastal settlements alerted.',
      affectedPopulationEst: 62000,
      source: 'Gujarat State Disaster Management Authority (GSDMA)',
      declaredAt: new Date(Date.now() - 9 * 3600 * 1000),
    },
    {
      title: 'Bellandur Lake Basin Urban Flash Flood Alert',
      type: 'URBAN_EMERGENCY',
      severity: 'MEDIUM',
      status: 'ACTIVE',
      locationName: 'Bellandur & Outer Ring Road Tech Corridor, Bengaluru',
      latitude: 12.9716,
      longitude: 77.5946,
      radiusKm: 12.0,
      description:
        'Cloudburst over eastern corridor caused storm drains to overflow into arterial roads. Bellandur and Outer Ring Road tech corridors flooded with traffic diversions in effect.',
      affectedPopulationEst: 70000,
      source: 'BBMP Disaster Management Cell & KSNDMC',
      declaredAt: new Date(Date.now() - 4 * 3600 * 1000),
    },
  ];

  const createdDisasters = [];
  for (const d of disastersData) {
    const created = await db.disaster.create({ data: d });
    createdDisasters.push(created);
  }
  console.log(`✓ Active Disasters created: ${createdDisasters.length} across Pan-India`);

  const primaryDisaster = createdDisasters[0]; // Assam
  const delhiDisaster = createdDisasters[1];
  const ukDisaster = createdDisasters[2];
  const odishaDisaster = createdDisasters[4];
  const mumbaiDisaster = createdDisasters[5];
  const keralaDisaster = createdDisasters[6];
  const chennaiDisaster = createdDisasters[7];

  // 3. Seed Pan-India Verified Safe Zones & Shelters
  const safeZonesData = [
    {
      name: 'Saroo Sajai Stadium Relief Complex',
      type: 'Sports Complex',
      locationName: 'Lokhra Road, Saroo Sajai, Guwahati, Assam',
      latitude: 26.1158,
      longitude: 91.7610,
      capacityTotal: 3500,
      capacityOccupied: 840,
      status: 'OPEN',
      amenities: JSON.stringify(['Drinking Water', 'Medical Post', 'Food Supply', 'Bedding', 'Emergency Power']),
      contactPerson: 'Col. P. Bordoloi (Camp Lead)',
      contactPhone: '+91 94350 22331',
      elevationMeters: 56.0,
      source: 'District Administration Kamrup Metro',
    },
    {
      name: 'Thyagaraj Sports Complex Emergency Shelter',
      type: 'Sports Complex',
      locationName: 'INA Colony, New Delhi',
      latitude: 28.5772,
      longitude: 77.2185,
      capacityTotal: 5000,
      capacityOccupied: 1200,
      status: 'OPEN',
      amenities: JSON.stringify(['Drinking Water', 'Air Conditioning', 'Medical Triage', 'Food Supply', 'Backup Generators']),
      contactPerson: 'Dr. Vivek Mehra (Nodal Officer)',
      contactPhone: '+91 98100 45678',
      elevationMeters: 216.0,
      source: 'Delhi Disaster Management Authority',
    },
    {
      name: 'Akshardham High-Ground Evacuation Camp',
      type: 'High Ground',
      locationName: 'East Delhi Riverbed Bypass, New Delhi',
      latitude: 28.6127,
      longitude: 77.2773,
      capacityTotal: 4000,
      capacityOccupied: 1650,
      status: 'OPEN',
      amenities: JSON.stringify(['Drinking Water', 'First Aid Tent', 'Hot Cooked Meals', 'Mobile Toilets', 'Lighting Towers']),
      contactPerson: 'Inspector Anita Rathi',
      contactPhone: '+91 98711 98765',
      elevationMeters: 212.0,
      source: 'East Delhi District Administration',
    },
    {
      name: 'Bandra-Kurla Complex (BKC) Emergency Center',
      type: 'Exhibition Center',
      locationName: 'MMRDA Grounds, BKC, Bandra East, Mumbai',
      latitude: 19.0657,
      longitude: 72.8687,
      capacityTotal: 6000,
      capacityOccupied: 2100,
      status: 'OPEN',
      amenities: JSON.stringify(['Food', 'Medical Unit', 'Drinking Water', 'Mobile Charging', 'Sanitary Facilities']),
      contactPerson: 'Sanjay Deshmukh (BMC Deputy Commissioner)',
      contactPhone: '+91 98200 33445',
      elevationMeters: 14.0,
      source: 'Brihanmumbai Municipal Corporation (BMC)',
    },
    {
      name: 'Andheri Sports Complex Relief Camp',
      type: 'Community Center',
      locationName: 'Veera Desai Road, Andheri West, Mumbai',
      latitude: 19.1293,
      longitude: 72.8338,
      capacityTotal: 4500,
      capacityOccupied: 980,
      status: 'OPEN',
      amenities: JSON.stringify(['Drinking Water', 'Bedding', 'Doctor on Duty', 'Dry Rations', 'Sanitation']),
      contactPerson: 'Kiran Kulkarni',
      contactPhone: '+91 98211 77665',
      elevationMeters: 18.0,
      source: 'BMC Disaster Cell K-West Ward',
    },
    {
      name: 'Kalinga Stadium Disaster Evacuation Center',
      type: 'Sports Complex',
      locationName: 'Bidyut Marg, Nayapalli, Bhubaneswar, Odisha',
      latitude: 20.2961,
      longitude: 85.8245,
      capacityTotal: 7500,
      capacityOccupied: 1850,
      status: 'OPEN',
      amenities: JSON.stringify(['Drinking Water', 'Full Kitchen', '24/7 Medical Squad', 'Power Backup', 'Emergency Beds']),
      contactPerson: 'Bhabani Sankar Chayani (OSDMA)',
      contactPhone: '+91 94370 12890',
      elevationMeters: 45.0,
      source: 'Odisha State Disaster Management Authority',
    },
    {
      name: 'Multi-Purpose Cyclone Shelter #12',
      type: 'Cyclone Shelter',
      locationName: 'Marine Drive Road, Puri Beach Sector, Odisha',
      latitude: 19.8050,
      longitude: 85.8200,
      capacityTotal: 2500,
      capacityOccupied: 1420,
      status: 'NEAR_CAPACITY',
      amenities: JSON.stringify(['Reinforced Concrete Bunker', 'Rooftop Helipad', 'RO Drinking Water', 'Solar Power']),
      contactPerson: 'Tapan Kumar Mishra (Shelter Incharge)',
      contactPhone: '+91 94380 55443',
      elevationMeters: 12.0,
      source: 'Puri District Administration & OSDMA',
    },
    {
      name: 'Wayanad St. Joseph Community Relief Camp',
      type: 'Community Center',
      locationName: 'Meppadi High School Road, Wayanad, Kerala',
      latitude: 11.5540,
      longitude: 76.1280,
      capacityTotal: 2200,
      capacityOccupied: 1680,
      status: 'NEAR_CAPACITY',
      amenities: JSON.stringify(['First Aid Clinic', 'Trauma Counseling', 'Drinking Water', 'Food Supply', 'Bedding']),
      contactPerson: 'Fr. George Thomas / Dr. Radhika Nair',
      contactPhone: '+91 94470 65432',
      elevationMeters: 780.0,
      source: 'Wayanad District Collectorate',
    },
    {
      name: 'Jawaharlal Nehru Indoor Stadium Evacuation Camp',
      type: 'Stadium',
      locationName: 'Sydenhams Road, Periamet, Chennai, Tamil Nadu',
      latitude: 13.0837,
      longitude: 80.2745,
      capacityTotal: 5500,
      capacityOccupied: 1340,
      status: 'OPEN',
      amenities: JSON.stringify(['Emergency Power', 'RO Drinking Water', 'Hot Meals', 'Medical Center', 'Blankets']),
      contactPerson: 'S. Ramanathan (TNSDMA)',
      contactPhone: '+91 94440 88776',
      elevationMeters: 9.0,
      source: 'Greater Chennai Corporation',
    },
    {
      name: 'Salt Lake Stadium Multi-Purpose Relief Hub',
      type: 'Stadium',
      locationName: 'JB Block, Sector III, Bidhannagar, Kolkata, West Bengal',
      latitude: 22.5697,
      longitude: 88.4069,
      capacityTotal: 8000,
      capacityOccupied: 2200,
      status: 'OPEN',
      amenities: JSON.stringify(['Drinking Water', 'Medical Unit', 'Community Kitchen', 'Sanitation', 'Ambulance Station']),
      contactPerson: 'Subir Mukherjee (WBDM)',
      contactPhone: '+91 98300 44556',
      elevationMeters: 11.0,
      source: 'West Bengal Disaster Management Department',
    },
    {
      name: 'Gandhi Maidan Disaster Evacuation Center',
      type: 'Community Ground',
      locationName: 'Fraser Road, Patna, Bihar',
      latitude: 25.6170,
      longitude: 85.1430,
      capacityTotal: 6500,
      capacityOccupied: 2900,
      status: 'OPEN',
      amenities: JSON.stringify(['Drinking Water', 'Disaster Tents', 'Medical Triage', 'Cooked Meals', 'Lighting Towers']),
      contactPerson: 'Rameshwar Singh (Patna DM Office)',
      contactPhone: '+91 94310 99887',
      elevationMeters: 53.0,
      source: 'Bihar State Disaster Management Authority',
    },
    {
      name: 'Rishikesh IDPL Evacuation Shelter',
      type: 'Community Complex',
      locationName: 'IDPL Township, Virbhadra, Rishikesh, Uttarakhand',
      latitude: 30.0869,
      longitude: 78.2676,
      capacityTotal: 3000,
      capacityOccupied: 650,
      status: 'OPEN',
      amenities: JSON.stringify(['Drinking Water', 'Medical First Aid', 'Warm Blankets', 'Dry Food Rations', 'Power Backup']),
      contactPerson: 'Capt. Dinesh Rawat',
      contactPhone: '+91 94120 77889',
      elevationMeters: 360.0,
      source: 'Dehradun & Tehri District Administration',
    },
    {
      name: 'Sardar Patel Multi-Purpose Relief Camp',
      type: 'Community Center',
      locationName: 'Navrangpura, Ahmedabad, Gujarat',
      latitude: 23.0373,
      longitude: 72.5613,
      capacityTotal: 4000,
      capacityOccupied: 890,
      status: 'OPEN',
      amenities: JSON.stringify(['Drinking Water', 'Medical Aid', 'Power', 'Hot Meals', 'Sanitation']),
      contactPerson: 'Harsh Patel',
      contactPhone: '+91 98250 11223',
      elevationMeters: 52.0,
      source: 'Ahmedabad Municipal Corporation (AMC)',
    },
    {
      name: 'Kanteerava Indoor Stadium Relief Camp',
      type: 'Sports Complex',
      locationName: 'Kasturba Road, Sampangi Rama Nagara, Bengaluru, Karnataka',
      latitude: 12.9698,
      longitude: 77.5926,
      capacityTotal: 4500,
      capacityOccupied: 720,
      status: 'OPEN',
      amenities: JSON.stringify(['Drinking Water', 'Emergency Bunk Beds', 'Medical Officer', 'Food Kits', 'Power Generators']),
      contactPerson: 'Manjunath Swamy',
      contactPhone: '+91 94480 33221',
      elevationMeters: 915.0,
      source: 'BBMP Disaster Management Unit',
    },
  ];

  for (const sz of safeZonesData) {
    await db.safeZone.create({ data: sz });
  }
  console.log(`✓ Safe Zones created: ${safeZonesData.length} across Pan-India`);

  // 4. Seed Pan-India Emergency Resources (Hospitals, NDRF Units, Fire Bases)
  const resourcesData = [
    {
      name: 'Gauhati Medical College & Hospital (GMCH)',
      category: 'HOSPITAL',
      locationName: 'Narakasur Hilltop, Bhangagarh, Guwahati, Assam',
      latitude: 26.1550,
      longitude: 91.7700,
      contactNumber: '+91 361 2529457',
      status: 'AVAILABLE',
      details: 'Level-1 Trauma & Emergency Care Unit operational with elevated triage ward.',
      supplies: JSON.stringify({ emergencyBeds: 120, icuBeds: 24, ambulances: 8, oxygenAvailability: 'High' }),
      source: 'Directorate of Health Services, Assam',
    },
    {
      name: 'NDRF 1st Battalion Base (Patgaon)',
      category: 'NDRF_UNIT',
      locationName: 'Patgaon, Rani Gate, Guwahati, Assam',
      latitude: 26.1150,
      longitude: 91.6050,
      contactNumber: '+91 361 2849005',
      status: 'ENGAGED',
      details: 'Deep water rescue teams actively deployed for boat evacuations along river corridor.',
      supplies: JSON.stringify({ inflatableRescueBoats: 14, deepDivers: 18, medicalFirstResponders: 60 }),
      source: 'National Disaster Response Force HQ',
    },
    {
      name: 'AIIMS New Delhi Level-1 Apex Trauma Center',
      category: 'HOSPITAL',
      locationName: 'Ansari Nagar, New Delhi',
      latitude: 28.5672,
      longitude: 77.2100,
      contactNumber: '011-26588500 / 102',
      status: 'AVAILABLE',
      details: 'Premier national trauma center with 24/7 mass casualty response team and disaster ward.',
      supplies: JSON.stringify({ traumaBeds: 250, icuBeds: 60, bloodUnitsAvailable: 450, ambulances: 15 }),
      source: 'Ministry of Health & Family Welfare',
    },
    {
      name: 'NDRF 8th Battalion HQ (Ghaziabad / NCR Base)',
      category: 'NDRF_UNIT',
      locationName: 'Govindpuram, Ghaziabad, Uttar Pradesh / NCR',
      latitude: 28.6692,
      longitude: 77.4538,
      contactNumber: '+91 120 2766014',
      status: 'AVAILABLE',
      details: 'Specialized Chemical, Biological, Radiological, and Urban Search & Rescue teams on 15-min standby.',
      supplies: JSON.stringify({ rescueVehicles: 22, boatTeams: 12, collapseSearchDogs: 8, hazmatUnits: 4 }),
      source: 'NDRF Directorate General',
    },
    {
      name: 'King Edward Memorial Hospital (KEM)',
      category: 'HOSPITAL',
      locationName: 'Acharya Donde Marg, Parel, Mumbai, Maharashtra',
      latitude: 19.0028,
      longitude: 72.8427,
      contactNumber: '022-24107000 / 108',
      status: 'AVAILABLE',
      details: 'Major civic hospital with specialized flood-triage protocol and high-capacity decontamination.',
      supplies: JSON.stringify({ disasterBeds: 180, ventilators: 35, mobileMedicalUnits: 6 }),
      source: 'BMC Public Health Department',
    },
    {
      name: 'NDRF 5th Battalion Unit (Pune / Mumbai Base)',
      category: 'NDRF_UNIT',
      locationName: 'Sudumbare, Maval, Pune / Mumbai Highway corridor',
      latitude: 18.7180,
      longitude: 73.6820,
      contactNumber: '+91 2114 247000',
      status: 'ENGAGED',
      details: 'Fast response teams deployed across Mumbai, Thane, and Raigad coastal zones.',
      supplies: JSON.stringify({ floodBoats: 16, hydraulicCutters: 12, searchCameras: 6 }),
      source: 'NDRF 5th Battalion Command',
    },
    {
      name: 'AIIMS Bhubaneswar Super Specialty Hospital',
      category: 'HOSPITAL',
      locationName: 'Sijua, Patrapada, Bhubaneswar, Odisha',
      latitude: 20.2312,
      longitude: 85.7766,
      contactNumber: '+91 674 2476789',
      status: 'AVAILABLE',
      details: 'Level-1 Cyclone-hardened trauma center with underground power grids and oxygen reserves.',
      supplies: JSON.stringify({ emergencyBeds: 160, icuBeds: 40, emergencyGenerators: 4 }),
      source: 'AIIMS Bhubaneswar Disaster Committee',
    },
    {
      name: 'NDRF 3rd Battalion Base (Mundali)',
      category: 'NDRF_UNIT',
      locationName: 'Mundali, Cuttack, Odisha',
      latitude: 20.4437,
      longitude: 85.7725,
      contactNumber: '+91 671 2879499',
      status: 'ENGAGED',
      details: 'Specialized coastal cyclone and deep water rescue units deployed along Paradip and Puri.',
      supplies: JSON.stringify({ motorizedBoats: 24, treeCutters: 40, emergencySatelliteComms: 10 }),
      source: 'NDRF 3rd Battalion Command',
    },
    {
      name: 'Aster Medcity Disaster Response Wing',
      category: 'HOSPITAL',
      locationName: 'Kuttisahib Road, Cheranallur, Kochi, Kerala',
      latitude: 10.0528,
      longitude: 76.2731,
      contactNumber: '+91 484 6699999',
      status: 'AVAILABLE',
      details: 'Waterfront hospital with helipad emergency airlift capability and disaster ICU.',
      supplies: JSON.stringify({ icuBeds: 50, airAmbulanceStandby: true, floodEvacBeds: 90 }),
      source: 'Kerala Health Services',
    },
    {
      name: 'NDRF 4th Battalion Operations Base',
      category: 'NDRF_UNIT',
      locationName: 'Suraksha Campus, Arakkonam, Tamil Nadu (Kerala-TN Corridor)',
      latitude: 13.0800,
      longitude: 79.6700,
      contactNumber: '+91 4177 232000',
      status: 'ENGAGED',
      details: 'Mountain rescue squads and canine search units deployed to Wayanad landslide disaster.',
      supplies: JSON.stringify({ mountainRescueKits: 30, groundPenetratingRadar: 4, lifeDetectors: 8 }),
      source: 'NDRF 4th Battalion HQ',
    },
    {
      name: 'Rajiv Gandhi Government General Hospital',
      category: 'HOSPITAL',
      locationName: 'EVR Periyar Salai, Park Town, Chennai, Tamil Nadu',
      latitude: 13.0805,
      longitude: 80.2785,
      contactNumber: '044-25305000 / 108',
      status: 'AVAILABLE',
      details: 'Apex government medical facility with elevated flood-proof critical trauma towers.',
      supplies: JSON.stringify({ traumaBeds: 200, icuBeds: 45, emergencyAmbulances: 12 }),
      source: 'Tamil Nadu Health Department',
    },
    {
      name: 'SSKM Hospital & IPGMER Level-1 Trauma Center',
      category: 'HOSPITAL',
      locationName: 'AJC Bose Road, Bhowanipore, Kolkata, West Bengal',
      latitude: 22.5393,
      longitude: 88.3426,
      contactNumber: '033-22231589 / 102',
      status: 'AVAILABLE',
      details: 'Eastern India premier trauma and surgical disaster hub with rapid triage capacity.',
      supplies: JSON.stringify({ emergencyBeds: 175, icuBeds: 38, antiVenomUnits: 300 }),
      source: 'West Bengal Health Services',
    },
    {
      name: 'NDRF 2nd Battalion Regional Base',
      category: 'NDRF_UNIT',
      locationName: 'Haringhata, Nadia, West Bengal',
      latitude: 22.9567,
      longitude: 88.5432,
      contactNumber: '+91 3473 245001',
      status: 'AVAILABLE',
      details: 'Riverine and coastal storm response units equipped with amphibious rescue crafts.',
      supplies: JSON.stringify({ inflatableBoats: 20, highCapacityDewateringPumps: 15 }),
      source: 'NDRF 2nd Battalion Command',
    },
    {
      name: 'AIIMS Rishikesh Emergency Care Unit',
      category: 'HOSPITAL',
      locationName: 'Virbhadra Road, Rishikesh, Uttarakhand',
      latitude: 30.0760,
      longitude: 78.2880,
      contactNumber: '+91 135 2462929',
      status: 'AVAILABLE',
      details: 'High-altitude trauma center with helipad, hyperbaric chambers, and severe trauma surgery.',
      supplies: JSON.stringify({ mountainTraumaBeds: 90, icuBeds: 25, airEvacuationHeliTeam: true }),
      source: 'AIIMS Rishikesh Emergency Medicine',
    },
    {
      name: 'Civil Hospital Ahmedabad Apex Trauma Center',
      category: 'HOSPITAL',
      locationName: 'Asarwa, Ahmedabad, Gujarat',
      latitude: 23.0530,
      longitude: 72.6025,
      contactNumber: '079-22683721 / 108',
      status: 'AVAILABLE',
      details: 'One of Asia largest hospital complexes with dedicated mass-disaster pavilion.',
      supplies: JSON.stringify({ emergencyBeds: 300, icuBeds: 70, disasterResponseAmbulances: 18 }),
      source: 'Gujarat Health Department',
    },
    {
      name: 'NDRF 6th Battalion Base',
      category: 'NDRF_UNIT',
      locationName: 'Jarod, Vadodara, Gujarat',
      latitude: 22.3072,
      longitude: 73.1812,
      contactNumber: '+91 2668 274444',
      status: 'AVAILABLE',
      details: 'Cyclone and earthquake rescue task force on state-wide standby.',
      supplies: JSON.stringify({ rescueVans: 14, structuralCollapseKits: 10, deepCutters: 12 }),
      source: 'NDRF 6th Battalion Command',
    },
    {
      name: 'AIIMS Patna Emergency Trauma Center',
      category: 'HOSPITAL',
      locationName: 'Aurangabad Road, Phulwari Sharif, Patna, Bihar',
      latitude: 25.5606,
      longitude: 85.0483,
      contactNumber: '+91 612 2451000',
      status: 'AVAILABLE',
      details: 'Equipped with flood epidemic control unit, infectious disease ward, and trauma care.',
      supplies: JSON.stringify({ floodTriageBeds: 120, icuBeds: 30, oralRehydrationSupplies: 'High' }),
      source: 'AIIMS Patna Disaster Board',
    },
    {
      name: 'NDRF 9th Battalion Base (Bihta)',
      category: 'NDRF_UNIT',
      locationName: 'Bihta Air Force Station Area, Patna, Bihar',
      latitude: 25.5684,
      longitude: 84.8690,
      contactNumber: '+91 6115 252002',
      status: 'ENGAGED',
      details: 'Leading active boat rescue operations in Kosi and Ganga flood-affected districts.',
      supplies: JSON.stringify({ motorizedBoats: 28, waterRescueSpecialists: 110 }),
      source: 'NDRF 9th Battalion Command',
    },
    {
      name: 'Victoria Hospital Emergency & Trauma Care',
      category: 'HOSPITAL',
      locationName: 'Fort Road, Near City Market, Bengaluru, Karnataka',
      latitude: 12.9629,
      longitude: 77.5753,
      contactNumber: '080-26701150 / 108',
      status: 'AVAILABLE',
      details: 'Central Bengaluru emergency hospital with burn center and trauma resuscitation unit.',
      supplies: JSON.stringify({ emergencyBeds: 140, icuBeds: 28, traumaSurgicalSuites: 4 }),
      source: 'Karnataka Health & Family Welfare',
    },
  ];

  for (const res of resourcesData) {
    await db.emergencyResource.create({ data: res });
  }
  console.log(`✓ Emergency Resources created: ${resourcesData.length} across Pan-India`);

  // 5. Seed Pan-India Incident Reports
  const reportsData = [
    {
      trackingCode: 'RPT-2026-0001',
      disasterId: primaryDisaster.id,
      citizenId: citizenUser.id,
      citizenName: 'Abhinav Verma',
      citizenPhone: '+91 98765 43210',
      disasterType: 'FLOOD',
      title: 'Water rapidly entering ground floor near Bharalu River bridge',
      description:
        'Sluice gate backflow is causing water to surge into residential lane #3. 4 elderly citizens stranded on rooftop.',
      locationName: 'Bharalumukh, Guwahati, Assam',
      latitude: 26.1740,
      longitude: 91.7380,
      imageUrl: null,
      status: 'PENDING_VERIFICATION',
      triagePriority: 'HIGH',
    },
    {
      trackingCode: 'RPT-2026-0002',
      disasterId: primaryDisaster.id,
      citizenId: null,
      citizenName: 'Local Shopkeeper (Anonymous)',
      citizenPhone: '+91 94351 98765',
      disasterType: 'FLOOD',
      title: 'Road embankment collapsed on Jalukbari arterial road',
      description:
        'Road culvert caved in under intense drainage overflow. Traffic fully blocked; emergency vehicles cannot pass.',
      locationName: 'Jalukbari Point, Guwahati, Assam',
      latitude: 26.1470,
      longitude: 91.6620,
      imageUrl: null,
      status: 'VERIFIED',
      triagePriority: 'CRITICAL',
      authorityNotes: 'Verified via Police Traffic CCTV feed. Traffic diversion activated towards NH-27 bypass.',
      verifiedById: authorityUser.id,
    },
    {
      trackingCode: 'RPT-2026-0003',
      disasterId: delhiDisaster.id,
      citizenId: null,
      citizenName: 'Rohit Sharma (Commuter)',
      citizenPhone: '+91 98101 23456',
      disasterType: 'FLOOD',
      title: 'Yamuna flood plain seep reaching Ring Road near Monastery market',
      description:
        'Floodwater is overflowing the drainage sluice and spreading onto the main carriageway. Water depth approx 2 feet.',
      locationName: 'Ring Road near Monastery Market, Kashmere Gate, New Delhi',
      latitude: 28.6670,
      longitude: 77.2340,
      imageUrl: null,
      status: 'VERIFIED',
      triagePriority: 'HIGH',
      authorityNotes: 'Traffic police notified. Pumping stations active.',
      verifiedById: authorityUser.id,
    },
    {
      trackingCode: 'RPT-2026-0004',
      disasterId: mumbaiDisaster.id,
      citizenId: null,
      citizenName: 'Priya Sawant (Resident)',
      citizenPhone: '+91 98205 67890',
      disasterType: 'URBAN_EMERGENCY',
      title: 'S.V. Road waterlogged 3 feet near Milan Subway',
      description:
        'Subway completely submerged. Two BEST buses stranded. Water entering nearby ground floor shops.',
      locationName: 'Milan Subway, Santacruz West, Mumbai',
      latitude: 19.0880,
      longitude: 72.8420,
      imageUrl: null,
      status: 'VERIFIED',
      triagePriority: 'HIGH',
      authorityNotes: 'Subway closed for vehicular traffic. De-watering pumps deployed.',
      verifiedById: authorityUser.id,
    },
    {
      trackingCode: 'RPT-2026-0005',
      disasterId: keralaDisaster.id,
      citizenId: null,
      citizenName: 'Manu Varghese (Plantation Worker)',
      citizenPhone: '+91 94475 11223',
      disasterType: 'LANDSLIDE',
      title: 'Soil fissure and heavy mudslide blocking Chooralmala access road',
      description:
        'Major earth slip from hillside covered 100 meters of road with mud and tree logs. 15 estate houses cut off from main village.',
      locationName: 'Chooralmala Valley Road, Meppadi, Wayanad, Kerala',
      latitude: 11.5450,
      longitude: 76.1350,
      imageUrl: null,
      status: 'VERIFIED',
      triagePriority: 'CRITICAL',
      authorityNotes: 'NDRF 4th Bn team and Army engineers dispatched with earthmovers.',
      verifiedById: authorityUser.id,
    },
    {
      trackingCode: 'RPT-2026-0006',
      disasterId: odishaDisaster.id,
      citizenId: null,
      citizenName: 'Bikram Jena (Fisherman)',
      citizenPhone: '+91 94371 88990',
      disasterType: 'CYCLONE',
      title: 'High sea waves breaching temporary sand barriers near Puri Lighthouse',
      description:
        'Sea water has entered beachside shacks and road. Wave height exceeding 3.5 meters with intense squalls.',
      locationName: 'Puri Beach Sector near Lighthouse, Odisha',
      latitude: 19.7920,
      longitude: 85.8150,
      imageUrl: null,
      status: 'VERIFIED',
      triagePriority: 'HIGH',
      authorityNotes: 'Red flags hoisted. Coastal police evacuated 120 vendors to Cyclone Shelter #12.',
      verifiedById: authorityUser.id,
    },
    {
      trackingCode: 'RPT-2026-0007',
      disasterId: ukDisaster.id,
      citizenId: null,
      citizenName: 'Devendra Negi (Taxi Driver)',
      citizenPhone: '+91 94125 33445',
      disasterType: 'LANDSLIDE',
      title: 'Massive boulders blocking Badrinath National Highway near Helang',
      description:
        'Shooting stones and boulders continuously falling from upper cliff. Approx 60 vehicles stranded on both sides.',
      locationName: 'NH-7 near Helang, Chamoli District, Uttarakhand',
      latitude: 30.5280,
      longitude: 79.5210,
      imageUrl: null,
      status: 'VERIFIED',
      triagePriority: 'CRITICAL',
      authorityNotes: 'BRO bulldozers deployed. Pilgrim vehicles diverted to designated halting points.',
      verifiedById: authorityUser.id,
    },
    {
      trackingCode: 'RPT-2026-0008',
      disasterId: chennaiDisaster.id,
      citizenId: null,
      citizenName: 'Karthik Subramanian',
      citizenPhone: '+91 94441 55667',
      disasterType: 'FLOOD',
      title: 'Velachery main road inundated up to car bonnet level',
      description:
        'Canal overflow combined with heavy localized rain caused water to enter apartments in Ram Nagar.',
      locationName: 'Velachery Main Road & Ram Nagar, Chennai, Tamil Nadu',
      latitude: 12.9780,
      longitude: 80.2180,
      imageUrl: null,
      status: 'PENDING_VERIFICATION',
      triagePriority: 'MEDIUM',
    },
    {
      trackingCode: 'RPT-2026-0009',
      disasterId: primaryDisaster.id,
      citizenId: null,
      citizenName: 'Sunil Paswan',
      citizenPhone: '+91 94315 77889',
      disasterType: 'FLOOD',
      title: 'Drainage pump failure causing waist-deep water in Rajendra Nagar',
      description:
        'Municipal pump out of fuel. Water stagnant for 8 hours; ground floor residents requesting food packets.',
      locationName: 'Rajendra Nagar Road #6, Patna, Bihar',
      latitude: 25.5990,
      longitude: 85.1610,
      imageUrl: null,
      status: 'VERIFIED',
      triagePriority: 'HIGH',
      authorityNotes: 'Diesel generator and backup mobile de-watering pump dispatched.',
      verifiedById: authorityUser.id,
    },
  ];

  for (const rpt of reportsData) {
    await db.incidentReport.create({ data: rpt });
  }
  console.log(`✓ Incident Reports created: ${reportsData.length} across Pan-India`);

  // 6. Seed Pan-India Broadcast Alerts
  const alertsData = [
    {
      disasterId: primaryDisaster.id,
      authorId: authorityUser.id,
      title: 'URGENT: Brahmaputra River Spillage Warning & Evacuation Order',
      type: 'EVACUATION_ORDER',
      severity: 'CRITICAL',
      status: 'ACTIVE',
      targetAreaName: 'Kamrup Metropolitan & Riverbank Wards 1-14, Assam',
      targetLatitude: 26.1445,
      targetLongitude: 91.7362,
      targetRadiusKm: 20.0,
      headline: 'IMMEDIATE EVACUATION ADVISED FOR RIVERBANK RESIDENTS',
      detailedMessage:
        'Brahmaputra water level continues to rise at 4cm/hour. All residents within 500m of river embankment are ordered to evacuate immediately to designated safe shelters. Do not attempt to cross flooded underpasses.',
      actionInstructions:
        '1. Switch off main electricity breakers.\n2. Carry identification, essential medicines, and torch.\n3. Move immediately towards Saroo Sajai Stadium Relief Camp.\n4. Call 1070 or 112 for NDRF water rescue.',
      source: 'Assam State Disaster Management Authority (ASDMA)',
      expiresAt: new Date(Date.now() + 24 * 3600 * 1000),
    },
    {
      disasterId: delhiDisaster.id,
      authorId: authorityUser.id,
      title: 'Yamuna River Basin Flood Advisory & Low-Lying Evacuation Directive',
      type: 'EVACUATION_ORDER',
      severity: 'HIGH',
      status: 'ACTIVE',
      targetAreaName: 'Yamuna Floodplain, Kashmere Gate, Mayur Vihar, New Delhi',
      targetLatitude: 28.6692,
      targetLongitude: 77.2315,
      targetRadiusKm: 18.0,
      headline: 'Yamuna river crossed danger mark 206.5m. Evacuate low-lying sectors.',
      detailedMessage:
        'Due to heavy release from Hathnikund Barrage, all settlements along Yamuna floodplains must shift immediately to higher ground relief camps.',
      actionInstructions:
        'Move to Thyagaraj Stadium or Akshardham relief camps. Keep cattle away from riverbanks. Dial 112 for emergency help.',
      source: 'Delhi Disaster Management Authority (DDMA)',
      expiresAt: new Date(Date.now() + 20 * 3600 * 1000),
    },
    {
      disasterId: odishaDisaster.id,
      authorId: authorityUser.id,
      title: 'Severe Cyclonic Storm "Sagar" Red Alert & Coastal Evacuation Order',
      type: 'EVACUATION_ORDER',
      severity: 'CRITICAL',
      status: 'ACTIVE',
      targetAreaName: 'Puri, Jagatsinghpur, Kendrapada Coastal Districts, Odisha',
      targetLatitude: 19.8135,
      targetLongitude: 85.8312,
      targetRadiusKm: 35.0,
      headline: 'Severe Cyclone landfall imminent with 120km/h winds & 2.5m storm surge.',
      detailedMessage:
        'Complete suspension of coastal transit and fishing. All residents living in kutcha houses within 5km of coastline must shift to multi-purpose cyclone shelters.',
      actionInstructions:
        'Take shelter in Cyclone Shelter #12 or Kalinga Stadium. Keep battery radios tuned to All India Radio. Follow ODRF instructions.',
      source: 'Odisha State Disaster Management Authority (OSDMA)',
      expiresAt: new Date(Date.now() + 30 * 3600 * 1000),
    },
    {
      disasterId: keralaDisaster.id,
      authorId: authorityUser.id,
      title: 'Wayanad Ghat Sector Landslide Red Warning & Mandatory Camp Movement',
      type: 'EVACUATION_ORDER',
      severity: 'CRITICAL',
      status: 'ACTIVE',
      targetAreaName: 'Chooralmala, Meppadi, Mundakkai, Wayanad, Kerala',
      targetLatitude: 11.5534,
      targetLongitude: 76.1320,
      targetRadiusKm: 16.0,
      headline: 'High risk of repeated debris flow on hill slopes. Evacuate immediately.',
      detailedMessage:
        'Extremely heavy rainfall continues over Western Ghats slopes. All families in high-hazard zones must move to St. Joseph Community Relief Camp immediately.',
      actionInstructions:
        'Do not stay in valleys or near river bridges. Follow NDRF search and rescue instructions. Call 1077 (District Control Room).',
      source: 'Kerala State Disaster Management Authority (KSDMA)',
      expiresAt: new Date(Date.now() + 16 * 3600 * 1000),
    },
    {
      disasterId: mumbaiDisaster.id,
      authorId: authorityUser.id,
      title: 'Mumbai Extreme Rainfall & Coastal High Tide Advisory',
      type: 'WARNING',
      severity: 'HIGH',
      status: 'ACTIVE',
      targetAreaName: 'Greater Mumbai, Thane & Navi Mumbai',
      targetLatitude: 19.0760,
      targetLongitude: 72.8777,
      targetRadiusKm: 25.0,
      headline: 'Astronomical high tide 4.87m combined with heavy rains.',
      detailedMessage:
        'Citizens are advised to avoid sea promenades (Marine Drive, Worli, Bandra Bandstand) and waterlogged underpasses.',
      actionInstructions:
        'Work from home recommended. Use Mumbai Police / BMC helpline 1916 for distress calls.',
      source: 'Brihanmumbai Municipal Corporation (BMC)',
      expiresAt: new Date(Date.now() + 12 * 3600 * 1000),
    },
  ];

  for (const alt of alertsData) {
    await db.alert.create({ data: alt });
  }
  console.log(`✓ Active Alerts created: ${alertsData.length} across Pan-India`);

  // 7. Seed Initial Risk Assessment
  await db.riskAssessment.create({
    data: {
      disasterId: primaryDisaster.id,
      locationName: 'Pan-India Multi-Hazard Operations Grid',
      latitude: 22.3511,
      longitude: 78.6677,
      riskLevel: 'SEVERE',
      riskScore: 89.2,
      floodRisk: 91.0,
      cycloneRisk: 84.0,
      landslideRisk: 78.0,
      confidenceScore: 0.94,
      modelVersion: 'TRINETRA-NATIONAL-RISK-v2.0',
      factorsJson: JSON.stringify([
        { name: 'Monsoon Depression Fronts', weight: 0.35, value: 'Active across Gangetic & Brahmaputra basins' },
        { name: 'Bay of Bengal Cyclonic Energy', weight: 0.35, value: 'Category-1 Severe Cyclonic Storm Sagar active' },
        { name: 'Western Ghats Geotechnical Saturation', weight: 0.30, value: 'Antecedent precipitation index > 92%' },
      ]),
      explanationText:
        'Compound multi-hazard modeling reveals simultaneous high-impact hydrometeorological events across Eastern, Northern, and Western sectors of India.',
      advisoryText:
        'Maintain highest level of alert across all State Disaster Management Authorities and mobilize NDRF regional battalions.',
      isFallback: false,
    },
  });

  // 8. Seed Operational Flood Buffers
  await db.floodBuffer.create({
    data: {
      name: 'Ayodhya Saryu River Flood Zone Model',
      geometryGeojson: '{"type":"Polygon","coordinates":[[[82.18,26.81],[82.22,26.81],[82.22,26.78],[82.18,26.78],[82.18,26.81]]]}',
      riskLevel: 'HIGH',
      source: 'Central Water Commission (CWC) Hydro-GIS',
    },
  });
  await db.floodBuffer.create({
    data: {
      name: 'Lucknow Gomti Basin Buffer',
      geometryGeojson: '{"type":"Polygon","coordinates":[[[80.90,26.86],[80.98,26.86],[80.98,26.83],[80.90,26.83],[80.90,26.86]]]}',
      riskLevel: 'MODERATE',
      source: 'Central Water Commission (CWC) Hydro-GIS',
    },
  });

  console.log('--- TRINETRA Pan-India Seed Completed Successfully! ---');
}
